### ISSUE TITLE
API response

### ISSUE THREAD

**Issue by olimart** [olimart/bento#79]
Didn't realize earlier but call to api/products raise errors.

First it was rendering to_json instead of jbuilder view, so I changed it, but now raising errors all over.

**Comment by croko** [comment]
Did you get error in development mode too?

**Comment by olimart** [comment]
no, production only.

Due to caching method that I removed yesterday b8902f795acfae0c8d02b25a705807081d26a82b
but caching should work, not sure why it creates so many caches.

**Comment by olimart** [comment]
Merged. Are we having shorter cache name with your code? What's the trick/issue?

**Comment by croko** [comment]
Linux file system has limited length for filenames, so I created MD5 hash of array of products ids. It should change if any id will change
