### ISSUE TITLE
Sort products in collection

### ISSUE THREAD

**Issue by olimart** [olimart/bento#84]
There is a bug when sorting products in collection.

Edit collection, rearrange products, save. It should work fine.
Then edit another collection, sort products again, save.
Return to first collection you edited, and products will no longer be sorted.

**Comment by croko** [comment]
can't reproduce. May be you have 2 collections with same slug

**Comment by olimart** [comment]
I don’t.

**Comment by croko** [comment]
> Then edit another collection, sort products again, save.

what you mean edit and save? I tried in /admin collections reorder with drag and all worked as expected.

**Comment by olimart** [comment]
you're right, no need to edit (since reorder happens on show page). Let me try to reproduce again.

**Comment by croko** [comment]
check collection's slug please. This is one way to update position in several collections

**Comment by croko** [comment]
did you reorder the same product in different collections?

**Comment by olimart** [comment]
Maybe.
