### ISSUE TITLE
Post data to external service

### ISSUE THREAD

**Issue by olimart** [olimart/bento#89]
Here is the problem. I need to send data to external uri, formatted a JSON string. I give up, need fresh eyes.

Check out http://requestb.in/19ayymq1?inspect#sn895w
Inspect RAW BODY, this is what I need.

Working example with  CURL

```
curl --include --request POST 'http://requestb.in/19ayymq1' --data 'data={"transaction":{"transaction_amount":"60.0", "transaction_currency":"cad", "transaction_order_id":"00001", "click_hash":"3fec88d9ca15e25d3884fc607b3cb95e"}, "transaction_detail":{"0":{"transaction_detail_item_sku":"37-75511-2", "transaction_detail_item_name":"Boîte à Bento Festive (Or / Gold)", "transaction_detail_item_amount":"45.0", "transaction_detail_item_quantity":1}, "1":{"transaction_detail_item_sku":"", "transaction_detail_item_name":"Boîte à Bento Cube (Orange)", "transaction_detail_item_amount":"15.0", "transaction_detail_item_quantity":1}}}'
```

Now, the problem is to get that programmatically. Check out `AffiliationFocusWorker`

So far, I get all the details about the order but sending out the formatted JSON string is not working.

**Rules**
- JSON string must be wrapped within variable named `data`
- I'd like to keep using `net/http` because already using it but we can use unirest or httpparty
- does not need to be pretty

**Stuff I've run into**
- `to_json` sends escaped JSON (but server does not expect `\`)
- Sending ruby hash not working either (server does not handle `=>`) 

Checkout branch `af`

**Comment by croko** [comment]
What should be in response? How could I test?

**Comment by olimart** [comment]
Well this is where it sucks.

If you send data to requestbin, and it matches what I sent you then it
should work. Else, we can post to the external service, response must be
200 and body/message empty (not good if you get "no message sent"). I will
then need to check on the service's dashboard to see if order is received.

You can make a few request to the external service and I will check a bit
later. Important, order ID must be unique. So maybe log on your end all
requests sent and I will tell which order IDs went through.

We can't rely on error message on their end since they don't send back any
error messages

Le dimanche 19 avril 2015, Gennady <notifications@github.com> a écrit :

> What should be in response? How could I test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olimart/bento/issues/89#issuecomment-94274788>.
>


-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by croko** [comment]
I post json and got "ok" in response body. I spent more then 1 hour to create order at all. Rake bs not works. @top_bento is nil and main page not works too

**Comment by olimart** [comment]
It's because you're missing some collections.

Also, I noticed setting model screws things up.

Ok is good if I remember correctly.

Le dimanche 19 avril 2015, Gennady <notifications@github.com> a écrit :

> I post json and got "ok" in response body. I spent more then 1 hour to
> create order at all. Rake bs not works. @top_bento is nil and main page not
> works too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olimart/bento/issues/89#issuecomment-94277608>.
>


-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by croko** [comment]
![screen shot 2015-04-19 at 16 45 19](https://cloud.githubusercontent.com/assets/333912/7219665/85a7e1d4-e6b3-11e4-8159-6ab1fc986363.png)

**Comment by olimart** [comment]
Open skype

Le dimanche 19 avril 2015, Gennady <notifications@github.com> a écrit :

> [image: screen shot 2015-04-19 at 16 45 19]
> <https://cloud.githubusercontent.com/assets/333912/7219665/85a7e1d4-e6b3-11e4-8159-6ab1fc986363.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olimart/bento/issues/89#issuecomment-94278475>.
>


-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by olimart** [comment]
Getting 400, bad request

Le dimanche 19 avril 2015, Gennady <notifications@github.com> a écrit :

> [image: screen shot 2015-04-19 at 16 45 19]
> <https://cloud.githubusercontent.com/assets/333912/7219665/85a7e1d4-e6b3-11e4-8159-6ab1fc986363.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olimart/bento/issues/89#issuecomment-94278475>.
>


-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by croko** [comment]
http or https?

**Comment by codeguardci** [comment]
https

-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by croko** [comment]
give me link to service please

**Comment by olimart** [comment]
it's in the code, commented out next to request bin url

**Comment by olimart** [comment]
Here is how I test it. From rails console I run `AffiliationFocusWorker.perform_async(2, '3fec88d9ca15e25d3884fc607b3cb95e')`
With requestbin, nothing is received. And since there is no log, I don't even know if the request is being sent out (sidekiq processes it as expected)

When I use affiliation focus, same error than yesterday. No data sent
```
ERROR - 2015-04-21 23:40:27 --> Aucun message JSON envoyé dans le call HTTP : 70.55.186.147
ERROR - 2015-04-21 23:40:27 --> []
ERROR - 2015-04-21 23:40:27 --> {"User-Agent":"Ruby","Host":"icq.affiliationfocus.com","Accept":"*\/*","Content-Length":"183","Accept-Encoding":"gzip;q=1.0,deflate;q=0.6,identity;q=0.3","Content-Type":"application\/json"}
```

**Comment by croko** [comment]
How I tested. I commented out sidekiq, change perform to self.perfom and call AffiliationFocusWorker.perform(2, '3fec88d9ca15e25d3884fc607b3cb95e') from console. After response added binding.pry and inspected response. I got "OK" and in response.body "no messages sent" or something like this. Any errors. Tried with backslashes and without - no difference.

**Comment by olimart** [comment]
- The plan is to use sidekiq. Why bypassing it?
- No requests logged on pastern so there is got sot to be something (especially since with affiliation focus returning message empty)
- There was a pattern (that you wrote) with `WebhookWorker` now both workers are different (I meant the code for net/http)

**Comment by croko** [comment]
> The plan is to use sidekiq. Why bypassing it?
It's difficult to test with sidekiq. If it works without, it should work with queue
 
> No requests logged on pastern so there is got sot to be something (especially since with affiliation focus returning message empty)
could you clarify?

> now both workers are different (I meant the code for net/http)
do you mean sdekiq broke code execution?

**Comment by olimart** [comment]
can you prove request is being sent to requestbin `http://requestb.in/1bespwc1`

**Comment by croko** [comment]
54:       response = http.start {|connection| connection.request(req) }
 => 55:       binding.pry
    56:       case response
    57:       when Net::HTTPSuccess, Net::HTTPRedirection
    58:         # success
    59:       else
    60:         puts "**** #{response.message} ****"

[1] pry(AffiliationFocusWorker)> response
=> #<Net::HTTPInternalServerError 500 INTERNAL SERVER ERROR readbody=true>
[2] pry(AffiliationFocusWorker)> exit
**** INTERNAL SERVER ERROR ****

**Comment by croko** [comment]
requestbin works?

**Comment by olimart** [comment]
no, check yourself. It's empty
http://requestb.in/1bespwc1?inspect

**Comment by croko** [comment]
sent to https://icq.affiliationfocus.com/client/transaction/
 50:
    51:       http = Net::HTTP.new(uri.hostname, uri.port)
    52:       http.use_ssl = true
    53:
    54:       response = http.start {|connection| connection.request(req) }
 => 55:       binding.pry
    56:       case response
    57:       when Net::HTTPSuccess, Net::HTTPRedirection
    58:         # success
    59:       else
    60:         puts "**** #{response.message} ****"

[1] pry(AffiliationFocusWorker)> response
=> #<Net::HTTPOK 200 OK readbody=true>
[2] pry(AffiliationFocusWorker)> response.body
=> "No message sent!"

**Comment by olimart** [comment]
> => "No message sent!"

means no message sent, therefore it's not right. (200 code is misleading)

We need to make sure it works on requestbin first.

**Comment by croko** [comment]
> We need to make sure it works on requestbin first.

this code worked before. I'll try ti find pb

**Comment by croko** [comment]
is this your service? (http://requestb.in/)

**Comment by olimart** [comment]
no

**Comment by croko** [comment]
looks like service not works

**Comment by olimart** [comment]
working fine `curl -X POST -d "fizz=buzz" http://requestb.in/1bespwc1`

**Comment by croko** [comment]
> means no message sent, therefore it's not right. (200 code is misleading)

I have no idea how it should works. It sends json without errors and got some response. You could provide more info

**Comment by olimart** [comment]
make it work to requestbin first. For now, it does not work at all.

**Comment by croko** [comment]
I sent your example
  bento git:(af) ✗ curl --include --request POST 'http://requestb.in/19ayymq1' --data 'data={"transaction":{"transaction_amount":"60.0", "transaction_currency":"cad", "transaction_order_id":"00001", "click_hash":"3fec88d9ca15e25d3884fc607b3cb95e"}, "transaction_detail":{"0":{"transaction_detail_item_sku":"37-75511-2", "transaction_detail_item_name":"Boîte à Bento Festive (Or / Gold)", "transaction_detail_item_amount":"45.0", "transaction_detail_item_quantity":1}, "1":{"transaction_detail_item_sku":"", "transaction_detail_item_name":"Boîte à Bento Cube (Orange)", "transaction_detail_item_amount":"15.0", "transaction_detail_item_quantity":1}}}'
HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: keep-alive
Server: gunicorn/18.0
Date: Wed, 22 Apr 2015 14:05:56 GMT
Content-Type: text/html
Content-Length: 291
Via: 1.1 vegur

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by olimart** [comment]
ok so the same request posted to affiliation focus is working

**Comment by olimart** [comment]
now we need to find why it works with curl but not with net/http and more important it should be code-driven not copy/paste

**Comment by croko** [comment]
> now we need to find why it works with curl but not with net/http

it not works with curl on my side

**Comment by olimart** [comment]
remove `" "` around url

**Comment by croko** [comment]
could you prepare curl string for https://icq.affiliationfocus.com/client/transaction for testing?

**Comment by olimart** [comment]
```
curl --include --request POST https://icq.affiliationfocus.com/client/transaction/ --data 'data={"transaction":{"transaction_amount":"60.0", "transaction_currency":"cad", "transaction_order_id":"00006", "click_hash":"3fec88d9ca15e25d3884fc607b3cb95e"}, "transaction_detail":{"0":{"transaction_detail_item_sku":"37-75511-2", "transaction_detail_item_name":"Boîte à Bento Festive (Or / Gold)", "transaction_detail_item_amount":"45.0", "transaction_detail_item_quantity":1}, "1":{"transaction_detail_item_sku":"", "transaction_detail_item_name":"Boîte à Bento Cube (Orange)", "transaction_detail_item_amount":"15.0", "transaction_detail_item_quantity":1}}}'
```

Remember `transaction_order_id ` must be unique

**Comment by croko** [comment]
request still not works
  bento git:(af) ✗ curl --include --request POST http://requestb.in/19ayymq1 --data 'data={"transaction":{"transaction_amount":"60.0", "transaction_currency":"cad", "transaction_order_id":"00001", "click_hash":"3fec88d9ca15e25d3884fc607b3cb95e"}, "transaction_detail":{"0":{"transaction_detail_item_sku":"37-75511-2", "transaction_detail_item_name":"Boîte à Bento Festive (Or / Gold)", "transaction_detail_item_amount":"45.0", "transaction_detail_item_quantity":1}, "1":{"transaction_detail_item_sku":"", "transaction_detail_item_name":"Boîte à Bento Cube (Orange)", "transaction_detail_item_amount":"15.0", "transaction_detail_item_quantity":1}}}'
HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: keep-alive
Server: gunicorn/18.0
Date: Wed, 22 Apr 2015 14:14:58 GMT
Content-Type: text/html
Content-Length: 291
Via: 1.1 vegur

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>

**Comment by croko** [comment]
I'll test https://icq.affiliationfocus.com/client/transaction with rest client and inspect reponse

**Comment by croko** [comment]
sent your curl string to icq.... 
Got No message sent!

**Comment by olimart** [comment]
I just tried again and it worked

curl response
```
HTTP/1.1 200 OK
Date: Wed, 22 Apr 2015 14:40:32 GMT
Server: Apache
Access-Control-Allow-Origin: *
Content-Length: 0
Connection: close
Content-Type: text/html

```

**Comment by croko** [comment]
> I just tried again and it worked

which one?

**Comment by olimart** [comment]
curl --include --request POST https://icq.affiliationfocus.com/client/transaction/ --data 'data={"transaction":{"transaction_amount":"60.0", "transaction_currency":"cad", "transaction_order_id":"00005", "click_hash":"3fec88d9ca15e25d3884fc607b3cb95e"}, "transaction_detail":{"0":{"transaction_detail_item_sku":"37-75511-2", "transaction_detail_item_name":"Boîte à Bento Festive (Or / Gold)", "transaction_detail_item_amount":"45.0", "transaction_detail_item_quantity":1}, "1":{"transaction_detail_item_sku":"", "transaction_detail_item_name":"Boîte à Bento Cube (Orange)", "transaction_detail_item_amount":"15.0", "transaction_detail_item_quantity":1}}}'

**Comment by croko** [comment]
> curl --include --request POST https://icq.affiliationfocus.com/client/transaction/ --data 'data=

it forks for me too. I inspected response. Body contains "No message sent!"

**Comment by croko** [comment]
HTTP/1.1 200 OK
Date: Wed, 22 Apr 2015 14:38:09 GMT
Server: Apache
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html
![screen shot 2015-04-22 at 17 46 46](https://cloud.githubusercontent.com/assets/333912/7277234/947fbf40-e917-11e4-8f1d-b8edf5ce7dcf.png)

**Comment by olimart** [comment]
if you don't change `transaction_order_id` then it does not work. Your request does not show up on icq dashboard. Send another one and let's see if you get the same response.

**Comment by croko** [comment]
sent order id 00126

**Comment by olimart** [comment]
ok, received correctly by icq. Same response ?

**Comment by croko** [comment]
yes

**Comment by croko** [comment]
check order 127

**Comment by olimart** [comment]
Looks like we're now getting SSL. Pull since I've made a few attempts.
I've followed this http://mislav.uniqpath.com/2013/07/ruby-openssl/

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

You can try on server the following:
```
AffiliationFocusWorker.perform_async(52, '3fec88d9ca15e25d3884fc607b3cb95e')
```

**Comment by croko** [comment]
the same server? icq....?

**Comment by olimart** [comment]
yes.

On Thursday, April 23, 2015, Gennady <notifications@github.com> wrote:
> the same server? icq....?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/tfbNWoNb6qbe5No2XRqYDzfyCn0aXpsBg4PzBtaeaJ-LP6kZ6xPh5GcW0cW8-2YgLBVE5p-nUc-pIem_dcANNz5Fnp_wuTmEtVmXo1gQ3mxiWW5lGxpy3ZgUQHcoOe1ZuFmSbsOOMyD0f98WCW7HVsACFmAUsA=s0-d-e1-ft#https://github.com/notifications/beacon/AAhbqt-qZL3J645s0HJptadX6dGn70Cqks5oCITVgaJpZM4EC48m.gif
>

-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by croko** [comment]
try now please. I guess need to restart server

**Comment by olimart** [comment]
Same, still stuck in sidekiq queue because of SSL issue.

**Comment by croko** [comment]
clear queue and create new request

**Comment by olimart** [comment]
already did. same.

**Comment by croko** [comment]
I successfully sent from console

**Comment by olimart** [comment]
server console ?

**Comment by croko** [comment]
yes, from production. but without sidekiq

**Comment by croko** [comment]
unicorn restarted?

**Comment by olimart** [comment]
unicorn restarts on deploy

**Comment by croko** [comment]
I didn't deploy, I directly edit file on server. restart unicorn
